/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiQuoteRouteImport } from './routes/api.quote'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas_.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/service-areas_/$slug',
  path: '/service-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/quote': typeof ApiQuoteRoute
  '/service-areas_/$slug': typeof ServiceAreasSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/robots.txt'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/api/quote'
    | '/service-areas/$slug'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/robots.txt'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/api/quote'
    | '/service-areas/$slug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/robots.txt'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/api/quote'
    | '/service-areas_/$slug'
    | '/services_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas_/$slug': {
      id: '/service-areas_/$slug'
      path: '/service-areas/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
